### ISSUE TITLE
installing with curl inside docker ubuntu container

### ISSUE THREAD

**Issue by menzenski** [stampery/mongoaudit#23]
I installed and ran mongoaudit inside a new docker container today and found the provided curl installation instructions incomplete.

Per the instructions, `curl -s https://mongoaud.it/install | bash` and `mongoaudit` should be enough, but I found that it needed to be made executable first. I needed to do `curl -s https://mongoaud.it/install | bash`, `chmod +x mongoaudit`, and `./mongoaudit`.

**Comment by aesedepece** [comment]
Hi @menzenski thanks for your feedback.
Could you provide Ubuntu and docker versions?

**Comment by menzenski** [comment]
Sorry, I should have included those in the first post.

```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   092cba3
 Built:        Wed Feb 15 21:34:55 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   092cba3
 Built:        Wed Feb 15 21:34:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
$ cat /etc/issue
Ubuntu 16.04.1 LTS \n \l
```
