### ISSUE TITLE
Add Footer to website regarding relationship with MongoDB Inc.

### ISSUE THREAD

**Issue by jfalken** [stampery/mongoaudit#44]
`https://github.com/stampery/mongoaudit` currently contains a footer that clarifies the tool's owner/maintainer and relationship w/ MongoDB Inc.

Please add a similar footer near the end of `http://www.mongoaud.it` so that both resources show the same message. Thanks!

**Comment by elecay** [comment]
`http://www.mongoaud.it` no longer exists
